apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: cleanup
      image: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/python:3.8
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/shared-workspace/*
