apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: run-nose-tests
      image: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/python:3.8
      workingDir: /workspace/shared-workspace
      script: |
        #!/bin/sh
        pip install nose
        nosetests tests/
