apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  tasks:
    - name: lint-task
      taskRef:
        name: lint-task
    - name: test-task
      taskRef:
        name: test-task
    - name: cleanup-task
      taskRef:
        name: cleanup-task
