apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cicd-pipeline-run
  namespace: cicd
spec:
  pipelineRef:
    name: cicd-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
