apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup

    - name: clone-source
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/Gowrirraj/final-project-cicd.git
        - name: deleteExisting
          value: "true"

    - name: nose-test
      taskRef:
        name: nose-test
      runAfter:
        - clone-source
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
