# .tekton/pipelinerun.yml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cicd-pipeline-run
  namespace: cicd
spec:
  pipelineRef:
    name: cicd-pipeline
  timeout: 1h0m0s
  serviceAccountName: pipeline
