apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cicd-pipeline
  namespace: cicd
spec:
  tasks:
    - name: lint
      taskRef:
        name: lint-task
    - name: nose-test
      taskRef:
        name: nose-test-task
      runAfter:
        - lint
    - name: cleanup
      taskRef:
        name: cleanup-task
      runAfter:
        - nose-test
