apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup

    - name: nose-test
      taskRef:
        name: nose-test
      runAfter:
        - cleanup

