apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: clean-up
      image: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/ubuntu:latest
      script: |
        #!/bin/sh
        echo "Cleaning up resources"
        rm -rf /workspace/shared-workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
    - name: run-nose-tests
      image: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/python:3.8
      script: |
        #!/bin/sh
        pip install nose
        nosetests /workspace/shared-workspace/tests
