name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Lint the code
        run: |
          flake8 .

  test:
    runs-on: harbor-core-doc-common-svc.apps.as0096.tre.nsn-rdnet.net/flowone/ubuntu:latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
